# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2000, 1000)
        MainWindow.setStyleSheet("QWidget#centralwidget {\n"
"    border-image: url(:/pic/Payment.png) 0 0 0 0 stretch stretch;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBoxHalf = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxHalf.setGeometry(QtCore.QRect(880, 290, 16, 16))
        self.checkBoxHalf.setText("")
        self.checkBoxHalf.setObjectName("checkBoxHalf")
        self.checkBoxFull = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxFull.setGeometry(QtCore.QRect(1080, 290, 16, 16))
        self.checkBoxFull.setText("")
        self.checkBoxFull.setObjectName("checkBoxFull")
        self.checkBoxBank = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxBank.setGeometry(QtCore.QRect(1140, 360, 16, 16))
        self.checkBoxBank.setText("")
        self.checkBoxBank.setObjectName("checkBoxBank")
        self.checkBoxCreditCard = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxCreditCard.setGeometry(QtCore.QRect(1140, 420, 16, 16))
        self.checkBoxCreditCard.setText("")
        self.checkBoxCreditCard.setObjectName("checkBoxCreditCard")
        self.pushButtonConfirm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonConfirm.setGeometry(QtCore.QRect(920, 560, 281, 61))
        self.pushButtonConfirm.setStyleSheet("border-radius: 15px;\n"
"border: 3px solid  #58827d;")
        self.pushButtonConfirm.setText("")
        self.pushButtonConfirm.setObjectName("pushButtonConfirm")
        self.splitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(290, 460, 451, 171))
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setHandleWidth(14)
        self.splitter.setObjectName("splitter")
        self.lineEditPackage = QtWidgets.QLineEdit(parent=self.splitter)
        self.lineEditPackage.setObjectName("lineEditPackage")
        self.lineEditTime = QtWidgets.QLineEdit(parent=self.splitter)
        self.lineEditTime.setObjectName("lineEditTime")
        self.lineEditRoom = QtWidgets.QLineEdit(parent=self.splitter)
        self.lineEditRoom.setObjectName("lineEditRoom")
        self.splitter_2 = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(190, 220, 531, 101))
        self.splitter_2.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter_2.setHandleWidth(16)
        self.splitter_2.setObjectName("splitter_2")
        self.lineEditName = QtWidgets.QLineEdit(parent=self.splitter_2)
        self.lineEditName.setObjectName("lineEditName")
        self.lineEditID = QtWidgets.QLineEdit(parent=self.splitter_2)
        self.lineEditID.setObjectName("lineEditID")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(840, 500, 321, 51))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2000, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
