# Form implementation generated from reading ui file 'booking.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1466, 871)
        MainWindow.setStyleSheet("QMainWindow{border-image:url(:/images/Booking.png);background-image:rbg(0,255,255)}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget {\n"
"    border-image:url(:/pic/Booking.png) 0 0 0 0 stretch stretch;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 390, 341, 221))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.radioButtonTudo = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButtonTudo.setMinimumSize(QtCore.QSize(0, 35))
        self.radioButtonTudo.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonTudo.setFont(font)
        self.radioButtonTudo.setStyleSheet("/* Trạng thái bình thường (Code gốc của mày) */\n"
"QRadioButton {\n"
"    background-color: rgb(203, 221, 209);\n"
"    border-radius: 15px;\n"
"    border: 3px solid #58827d;\n"
"    padding: 5px; /* Tao thêm nhẹ 5px padding để chữ không bị dính sát vào cái viền bo góc */\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) */\n"
"QRadioButton:hover {\n"
"    background-color: #1a6b61; /* Màu xanh sáng hơn một chút để nổi bật */\n"
"    border: 3px solid #73a6a0;/* Viền sáng lên đồng bộ với nút kia */\n"
"}\n"
"\n"
"/* Trạng thái khi click chuột bấm xuống (Pressed) */\n"
"QRadioButton:pressed {\n"
"    background-color: rgb(175, 198, 183); /* Nền chìm tối xuống khi bấm */\n"
"    border: 3px solid #3d5e5b; /* Viền tối đi đồng bộ với nút kia */\n"
"}")
        self.radioButtonTudo.setObjectName("radioButtonTudo")
        self.verticalLayout_13.addWidget(self.radioButtonTudo)
        self.radioButtonYoga = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButtonYoga.setMinimumSize(QtCore.QSize(0, 35))
        self.radioButtonYoga.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonYoga.setFont(font)
        self.radioButtonYoga.setStyleSheet("/* Trạng thái bình thường (Giữ nguyên 100% của mày) */\n"
"QRadioButton {\n"
"    background-color: rgb(165, 185, 172);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    border: 3px solid #58827d;\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) */\n"
"QRadioButton:hover {\n"
"    background-color: #1a6b61; /* Màu xanh sáng hơn một chút để nổi bật */\n"
"    border: 3px solid #73a6a0; /* Viền sáng lên đồng bộ với mấy nút kia */\n"
"}\n"
"")
        self.radioButtonYoga.setCheckable(True)
        self.radioButtonYoga.setAutoRepeatDelay(302)
        self.radioButtonYoga.setObjectName("radioButtonYoga")
        self.verticalLayout_13.addWidget(self.radioButtonYoga)
        self.radioButtonPilates = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButtonPilates.setMinimumSize(QtCore.QSize(0, 35))
        self.radioButtonPilates.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonPilates.setFont(font)
        self.radioButtonPilates.setStyleSheet("/* Trạng thái bình thường (Code gốc của mày) */\n"
"QRadioButton {\n"
"    background-color: rgb(203, 221, 209);\n"
"    border-radius: 15px;\n"
"    border: 3px solid #58827d;\n"
"    padding: 5px; /* Tao thêm nhẹ 5px padding để chữ không bị dính sát vào cái viền bo góc */\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) */\n"
"QRadioButton:hover {\n"
"    background-color: #1a6b61; /* Màu xanh sáng hơn một chút để nổi bật */\n"
"    border: 3px solid #73a6a0;/* Viền sáng lên đồng bộ với nút kia */\n"
"}\n"
"\n"
"/* Trạng thái khi click chuột bấm xuống (Pressed) */\n"
"QRadioButton:pressed {\n"
"    background-color: rgb(175, 198, 183); /* Nền chìm tối xuống khi bấm */\n"
"    border: 3px solid #3d5e5b; /* Viền tối đi đồng bộ với nút kia */\n"
"}")
        self.radioButtonPilates.setObjectName("radioButtonPilates")
        self.verticalLayout_13.addWidget(self.radioButtonPilates)
        self.radioButtonBoxing = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButtonBoxing.setMinimumSize(QtCore.QSize(0, 35))
        self.radioButtonBoxing.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonBoxing.setFont(font)
        self.radioButtonBoxing.setStyleSheet("/* Trạng thái bình thường (Giữ nguyên 100% của mày) */\n"
"QRadioButton {\n"
"    background-color: rgb(165, 185, 172);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    border: 3px solid #58827d;\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) */\n"
"QRadioButton:hover {\n"
"    background-color: #1a6b61; /* Màu xanh sáng hơn một chút để nổi bật */\n"
"    border: 3px solid #73a6a0; /* Viền sáng lên đồng bộ với mấy nút kia */\n"
"}\n"
"")
        self.radioButtonBoxing.setObjectName("radioButtonBoxing")
        self.verticalLayout_13.addWidget(self.radioButtonBoxing)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(60, 610, 351, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.radioButtonYes = QtWidgets.QRadioButton(parent=self.groupBox_4)
        self.radioButtonYes.setMinimumSize(QtCore.QSize(0, 35))
        self.radioButtonYes.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonYes.setFont(font)
        self.radioButtonYes.setStyleSheet("/* Trạng thái bình thường (Code gốc của mày) */\n"
"QRadioButton {\n"
"    background-color: rgb(203, 221, 209);\n"
"    border-radius: 15px;\n"
"    border: 3px solid #58827d;\n"
"    padding: 5px; /* Tao thêm nhẹ 5px padding để chữ không bị dính sát vào cái viền bo góc */\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) */\n"
"QRadioButton:hover {\n"
"    background-color: #1a6b61; /* Màu xanh sáng hơn một chút để nổi bật */\n"
"    border: 3px solid #73a6a0;/* Viền sáng lên đồng bộ với nút kia */\n"
"}\n"
"\n"
"/* Trạng thái khi click chuột bấm xuống (Pressed) */\n"
"QRadioButton:pressed {\n"
"    background-color: rgb(175, 198, 183); /* Nền chìm tối xuống khi bấm */\n"
"    border: 3px solid #3d5e5b; /* Viền tối đi đồng bộ với nút kia */\n"
"}")
        self.radioButtonYes.setObjectName("radioButtonYes")
        self.verticalLayout_12.addWidget(self.radioButtonYes)
        self.radioButtonNo = QtWidgets.QRadioButton(parent=self.groupBox_4)
        self.radioButtonNo.setMinimumSize(QtCore.QSize(0, 35))
        self.radioButtonNo.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonNo.setFont(font)
        self.radioButtonNo.setStyleSheet("/* Trạng thái bình thường (Giữ nguyên 100% của mày) */\n"
"QRadioButton {\n"
"    background-color: rgb(165, 185, 172);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    border: 3px solid #58827d;\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) */\n"
"QRadioButton:hover {\n"
"    background-color: #1a6b61; /* Màu xanh sáng hơn một chút để nổi bật */\n"
"    border: 3px solid #73a6a0; /* Viền sáng lên đồng bộ với mấy nút kia */\n"
"}\n"
"")
        self.radioButtonNo.setObjectName("radioButtonNo")
        self.verticalLayout_12.addWidget(self.radioButtonNo)
        self.verticalLayout_15.addLayout(self.verticalLayout_12)
        self.pushButtonDoneBooking = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDoneBooking.setGeometry(QtCore.QRect(1200, 640, 241, 61))
        self.pushButtonDoneBooking.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Sans HK Black")
        font.setPointSize(20)
        font.setItalic(False)
        self.pushButtonDoneBooking.setFont(font)
        self.pushButtonDoneBooking.setStyleSheet("/* Trạng thái bình thường (Giữ nguyên 100% của mày) */\n"
"QPushButton {\n"
"    color: #f6f6e9;\n"
"    background-color: #0f433d;\n"
"    font: 87 20pt \"Noto Sans HK Black\";\n"
"    border-radius: 30px;\n"
"    border: 3px solid #58827d;\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) */\n"
"QPushButton:hover {\n"
"    background-color: #1a6b61; /* Màu xanh sáng hơn một chút để nổi bật */\n"
"    border: 3px solid #73a6a0; /* Viền cũng sáng lên một chút cho đồng bộ */\n"
"}\n"
"\n"
"/* Thêm luôn trạng thái khi click (bấm xuống) cho nó xịn */\n"
"QPushButton:pressed {\n"
"    background-color: #0a2e2a; /* Nền tối đi khi bấm */\n"
"    border: 3px solid #3d5e5b; /* Viền tối đi */\n"
"}")
        self.pushButtonDoneBooking.setObjectName("pushButtonDoneBooking")
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(1200, 530, 241, 91))
        self.groupBox_5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.comboBoxRoom = QtWidgets.QComboBox(parent=self.groupBox_5)
        self.comboBoxRoom.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.comboBoxRoom.setFont(font)
        self.comboBoxRoom.setMouseTracking(True)
        self.comboBoxRoom.setAutoFillBackground(False)
        self.comboBoxRoom.setStyleSheet("/* Trạng thái bình thường (Base gốc của mày) */\n"
"QComboBox {\n"
"    background-color: rgb(203, 221, 209);\n"
"    border-radius: 15px;\n"
"    border: 3px solid #58827d;\n"
"    padding-left: 10px;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) y chang RadioButton */\n"
"QComboBox:hover {\n"
"    background-color: #1a6b61; \n"
"    border: 3px solid #73a6a0; \n"
"}\n"
"\n"
"/* Trạng thái khi click vào và lúc danh sách đang xổ xuống (Pressed / On) */\n"
"QComboBox:pressed, QComboBox:on {\n"
"    background-color: rgb(175, 198, 183); \n"
"    border: 3px solid #3d5e5b; \n"
"}")
        self.comboBoxRoom.setMaxCount(2147483645)
        self.comboBoxRoom.setDuplicatesEnabled(False)
        self.comboBoxRoom.setObjectName("comboBoxRoom")
        self.comboBoxRoom.addItem("")
        self.comboBoxRoom.addItem("")
        self.comboBoxRoom.addItem("")
        self.comboBoxRoom.addItem("")
        self.comboBoxRoom.addItem("")
        self.comboBoxRoom.addItem("")
        self.comboBoxRoom.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBoxRoom)
        self.groupBox_6 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(1200, 390, 241, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.groupBox_6)
        self.dateEdit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("background-color: rgb(203, 221, 209);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;\n"
"padding-left: 10px;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 12, 31), QtCore.QTime(17, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_8.addWidget(self.dateEdit)
        self.comboBoxTime = QtWidgets.QComboBox(parent=self.groupBox_6)
        self.comboBoxTime.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.comboBoxTime.setFont(font)
        self.comboBoxTime.setStyleSheet("/* Trạng thái bình thường (Base gốc của mày) */\n"
"QComboBox {\n"
"    background-color: rgb(203, 221, 209);\n"
"    border-radius: 15px;\n"
"    border: 3px solid #58827d;\n"
"    padding-left: 10px;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) y chang RadioButton */\n"
"QComboBox:hover {\n"
"    background-color: #1a6b61; \n"
"    border: 3px solid #73a6a0; \n"
"}\n"
"\n"
"/* Trạng thái khi click vào và lúc danh sách đang xổ xuống (Pressed / On) */\n"
"QComboBox:pressed, QComboBox:on {\n"
"    background-color: rgb(175, 198, 183); \n"
"    border: 3px solid #3d5e5b; \n"
"}")
        self.comboBoxTime.setObjectName("comboBoxTime")
        self.comboBoxTime.addItem("")
        self.comboBoxTime.addItem("")
        self.comboBoxTime.addItem("")
        self.comboBoxTime.addItem("")
        self.comboBoxTime.addItem("")
        self.comboBoxTime.addItem("")
        self.comboBoxTime.addItem("")
        self.verticalLayout_8.addWidget(self.comboBoxTime)
        self.listWidgetHuanLuyenVien = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidgetHuanLuyenVien.setGeometry(QtCore.QRect(420, 500, 761, 251))
        self.listWidgetHuanLuyenVien.setMaximumSize(QtCore.QSize(1450, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.listWidgetHuanLuyenVien.setFont(font)
        self.listWidgetHuanLuyenVien.setStyleSheet("background-color: rgb(203, 221, 209);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;")
        self.listWidgetHuanLuyenVien.setObjectName("listWidgetHuanLuyenVien")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(420, 390, 761, 90))
        self.groupBox_2.setMaximumSize(QtCore.QSize(1450, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.comboBoxHuanLuyenVien = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.comboBoxHuanLuyenVien.setMinimumSize(QtCore.QSize(700, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxHuanLuyenVien.setFont(font)
        self.comboBoxHuanLuyenVien.setStyleSheet("/* Trạng thái bình thường (Base gốc của mày) */\n"
"QComboBox {\n"
"    background-color: rgb(165, 185, 172);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px; /* Đã sửa 15p thành 15px nhé */\n"
"    border: 3px solid #58827d;\n"
"    padding-left: 10px; /* Thêm nhẹ cái này cho chữ nó không bị dính vào viền trái */\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) y chang mày yêu cầu */\n"
"QComboBox:hover {\n"
"    background-color: #1a6b61; /* Màu xanh sáng hơn */\n"
"    border: 3px solid #73a6a0; /* Viền sáng lên */\n"
"}\n"
"\n"
"/* Trạng thái khi click vào và lúc danh sách đang xổ xuống (Pressed / On) */\n"
"QComboBox:pressed, QComboBox:on {\n"
"    background-color: #124d45; /* Nền tối đi một tông so với hover khi mày bấm xổ xuống */\n"
"    border: 3px solid #3d5e5b; /* Viền cũng chìm màu xuống */\n"
"}")
        self.comboBoxHuanLuyenVien.setObjectName("comboBoxHuanLuyenVien")
        self.verticalLayout_19.addWidget(self.comboBoxHuanLuyenVien)
        self.pushButtonCancelBooking = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCancelBooking.setGeometry(QtCore.QRect(1200, 710, 241, 61))
        self.pushButtonCancelBooking.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Sans HK Black")
        font.setPointSize(20)
        font.setItalic(False)
        self.pushButtonCancelBooking.setFont(font)
        self.pushButtonCancelBooking.setStyleSheet("/* Trạng thái bình thường (Giữ nguyên 100% của mày) */\n"
"QPushButton {\n"
"    color: #f6f6e9;\n"
"    background-color: #0f433d;\n"
"    font: 87 20pt \"Noto Sans HK Black\";\n"
"    border-radius: 30px;\n"
"    border: 3px solid #58827d;\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) */\n"
"QPushButton:hover {\n"
"    background-color: #1a6b61; /* Màu xanh sáng hơn một chút để nổi bật */\n"
"    border: 3px solid #73a6a0; /* Viền cũng sáng lên một chút cho đồng bộ */\n"
"}\n"
"\n"
"/* Thêm luôn trạng thái khi click (bấm xuống) cho nó xịn */\n"
"QPushButton:pressed {\n"
"    background-color: #0a2e2a; /* Nền tối đi khi bấm */\n"
"    border: 3px solid #3d5e5b; /* Viền tối đi */\n"
"}")
        self.pushButtonCancelBooking.setObjectName("pushButtonCancelBooking")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1466, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.comboBoxRoom.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Lĩnh vực:"))
        self.radioButtonTudo.setText(_translate("MainWindow", "Tự do"))
        self.radioButtonYoga.setText(_translate("MainWindow", "Yoga"))
        self.radioButtonPilates.setText(_translate("MainWindow", "Pilates"))
        self.radioButtonBoxing.setText(_translate("MainWindow", "Boxing"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Thuê huấn luyện viên:"))
        self.radioButtonYes.setText(_translate("MainWindow", "Có"))
        self.radioButtonNo.setText(_translate("MainWindow", "Không"))
        self.pushButtonDoneBooking.setText(_translate("MainWindow", "Hoàn tất đặt lịch"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Chọn phòng:"))
        self.comboBoxRoom.setCurrentText(_translate("MainWindow", "Phòng Boxing B1"))
        self.comboBoxRoom.setItemText(0, _translate("MainWindow", "Phòng Pilates P01"))
        self.comboBoxRoom.setItemText(1, _translate("MainWindow", "Phòng Pilates P02"))
        self.comboBoxRoom.setItemText(2, _translate("MainWindow", "Phòng Yoga Master Y01"))
        self.comboBoxRoom.setItemText(3, _translate("MainWindow", "Phòng Yoga Master Y02"))
        self.comboBoxRoom.setItemText(4, _translate("MainWindow", "Phòng Boxing B1"))
        self.comboBoxRoom.setItemText(5, _translate("MainWindow", "Phòng Boxing B2"))
        self.comboBoxRoom.setItemText(6, _translate("MainWindow", "Không gian chung"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Thời gian:"))
        self.comboBoxTime.setItemText(0, _translate("MainWindow", "7h - 9h"))
        self.comboBoxTime.setItemText(1, _translate("MainWindow", "9h - 11h"))
        self.comboBoxTime.setItemText(2, _translate("MainWindow", "11h - 13h"))
        self.comboBoxTime.setItemText(3, _translate("MainWindow", "13h - 15h"))
        self.comboBoxTime.setItemText(4, _translate("MainWindow", "15h - 17h"))
        self.comboBoxTime.setItemText(5, _translate("MainWindow", "17h - 19h"))
        self.comboBoxTime.setItemText(6, _translate("MainWindow", "19h - 21h"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Huấn luyện viên"))
        self.pushButtonCancelBooking.setText(_translate("MainWindow", "Hủy đặt lịch"))
