# Form implementation generated from reading ui file 'D:\TuduylaptrinhN1\K25411_KTLT\DoAn(1)\ui\booking.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2000, 1000)
        MainWindow.setStyleSheet("QMainWindow{border-image:url(:/images/Booking.png);background-image:rbg(0,255,255)}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget {\n"
"    border-image: url(:/pic/ic4.png) 0 0 0 0 stretch stretch;\n"
"}url(:/pic/ic4.png)")
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(120, 480, 400, 287))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_2.setMinimumSize(QtCore.QSize(0, 35))
        self.radioButton_2.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("background-color: rgb(203, 221, 209);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;")
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_13.addWidget(self.radioButton_2)
        self.radioButton_4 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_4.setMinimumSize(QtCore.QSize(0, 35))
        self.radioButton_4.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setStyleSheet("background-color: rgb(165, 185, 172);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;\n"
"")
        self.radioButton_4.setCheckable(True)
        self.radioButton_4.setAutoRepeatDelay(302)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_13.addWidget(self.radioButton_4)
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_3.setMinimumSize(QtCore.QSize(0, 35))
        self.radioButton_3.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("background-color: rgb(203, 221, 209);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;")
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_13.addWidget(self.radioButton_3)
        self.radioButton = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton.setMinimumSize(QtCore.QSize(0, 35))
        self.radioButton.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("background-color: rgb(165, 185, 172);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;")
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_13.addWidget(self.radioButton)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(120, 780, 400, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.radioButton_6 = QtWidgets.QRadioButton(parent=self.groupBox_4)
        self.radioButton_6.setMinimumSize(QtCore.QSize(0, 35))
        self.radioButton_6.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setStyleSheet("background-color: rgb(203, 221, 209);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;")
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_12.addWidget(self.radioButton_6)
        self.radioButton_5 = QtWidgets.QRadioButton(parent=self.groupBox_4)
        self.radioButton_5.setMinimumSize(QtCore.QSize(0, 35))
        self.radioButton_5.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setStyleSheet("background-color: rgb(165, 185, 172);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;")
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_12.addWidget(self.radioButton_5)
        self.verticalLayout_15.addLayout(self.verticalLayout_12)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1470, 830, 300, 81))
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Sans HK Black")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Noto Sans HK Black\";\n"
"background-color: rgb(24, 78, 73);\n"
"border-radius: 30px;\n"
"border: 3px solid  #58827d;")
        self.pushButton.setObjectName("pushButton")
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(1470, 690, 300, 111))
        self.groupBox_5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.comboBox = QtWidgets.QComboBox(parent=self.groupBox_5)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setMouseTracking(False)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet("background-color: rgb(203, 221, 209);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;\n"
"padding-left: 10px;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.comboBox.setMaxCount(2147483645)
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox)
        self.groupBox_6 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(1470, 490, 300, 162))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.groupBox_6)
        self.dateEdit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("background-color: rgb(203, 221, 209);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;\n"
"padding-left: 10px;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2026, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_8.addWidget(self.dateEdit)
        self.comboBox_3 = QtWidgets.QComboBox(parent=self.groupBox_6)
        self.comboBox_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("background-color: rgb(203, 221, 209);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;\n"
"padding-left: 10px;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout_8.addWidget(self.comboBox_3)
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(590, 630, 800, 321))
        self.listWidget.setMaximumSize(QtCore.QSize(1450, 16777215))
        self.listWidget.setStyleSheet("background-color: rgb(203, 221, 209);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;")
        self.listWidget.setObjectName("listWidget")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(580, 490, 820, 90))
        self.groupBox_2.setMaximumSize(QtCore.QSize(1450, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.comboBox_2.setMinimumSize(QtCore.QSize(700, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("background-color: rgb(165, 185, 172);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;")
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_19.addWidget(self.comboBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2000, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Lĩnh vực:"))
        self.radioButton_2.setText(_translate("MainWindow", "Tự do"))
        self.radioButton_4.setText(_translate("MainWindow", "Yoga"))
        self.radioButton_3.setText(_translate("MainWindow", "Pilates"))
        self.radioButton.setText(_translate("MainWindow", "Boxing"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Thuê huấn luyện viên:"))
        self.radioButton_6.setText(_translate("MainWindow", "Có"))
        self.radioButton_5.setText(_translate("MainWindow", "Không"))
        self.pushButton.setText(_translate("MainWindow", "Hoàn tất đặt lịch"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Chọn phòng:"))
        self.comboBox.setCurrentText(_translate("MainWindow", "Phòng Boxing B1"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Phòng Pilates P01"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Phòng Pilates P02"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Phòng Yoga Master Y01"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Phòng Yoga Master Y02"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Phòng Boxing B1"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Phòng Boxing B2"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Không gian chung"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Thời gian:"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "7h - 9h"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "9h - 11h"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "11h - 13h"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "13h - 15h"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "15h - 17h"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "17h - 19h"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "19h - 21h"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Huấn luyện viên"))
