# Form implementation generated from reading ui file 'D:\TuduylaptrinhN1\Do-an-cuoi-ki-Nhom8_KTLT\ui\statistic\StatisticMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(839, 500)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget {\n"
"    border-image: url(:/newPrefix/Thongke.png) 0 0 0 0 stretch stretch;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButtonBack = QtWidgets.QPushButton(parent=self.widget_3)
        self.pushButtonBack.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButtonBack.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans HK Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButtonBack.setFont(font)
        self.pushButtonBack.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 12pt \"Noto Sans HK Black\";\n"
"background-color: rgb(24, 78, 73);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;")
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.horizontalLayout_7.addWidget(self.pushButtonBack)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(parent=self.widget_3)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(parent=self.widget)
        self.groupBox.setMinimumSize(QtCore.QSize(550, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayoutChart = QtWidgets.QVBoxLayout()
        self.verticalLayoutChart.setObjectName("verticalLayoutChart")
        self.verticalLayout_8.addLayout(self.verticalLayoutChart)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButtonTKgoitap = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButtonTKgoitap.setMinimumSize(QtCore.QSize(270, 50))
        self.pushButtonTKgoitap.setMaximumSize(QtCore.QSize(270, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonTKgoitap.setFont(font)
        self.pushButtonTKgoitap.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonTKgoitap.setStyleSheet("background-color: rgb(203, 221, 209);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;")
        self.pushButtonTKgoitap.setObjectName("pushButtonTKgoitap")
        self.verticalLayout_5.addWidget(self.pushButtonTKgoitap)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.pushButtonTKdoanhthu = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButtonTKdoanhthu.setMinimumSize(QtCore.QSize(270, 50))
        self.pushButtonTKdoanhthu.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonTKdoanhthu.setFont(font)
        self.pushButtonTKdoanhthu.setStyleSheet("background-color: rgb(165, 185, 172);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;\n"
"")
        self.pushButtonTKdoanhthu.setObjectName("pushButtonTKdoanhthu")
        self.verticalLayout_5.addWidget(self.pushButtonTKdoanhthu)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.pushButtonTKluongkhach = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButtonTKluongkhach.setMinimumSize(QtCore.QSize(270, 50))
        self.pushButtonTKluongkhach.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonTKluongkhach.setFont(font)
        self.pushButtonTKluongkhach.setStyleSheet("background-color: rgb(203, 221, 209);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;")
        self.pushButtonTKluongkhach.setObjectName("pushButtonTKluongkhach")
        self.verticalLayout_5.addWidget(self.pushButtonTKluongkhach)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 839, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonBack.setText(_translate("MainWindow", "Back"))
        self.groupBox.setTitle(_translate("MainWindow", "Chart Visualize:"))
        self.pushButtonTKgoitap.setText(_translate("MainWindow", "Thống kê gói tập"))
        self.pushButtonTKdoanhthu.setText(_translate("MainWindow", "Thống kê doanh thu"))
        self.pushButtonTKluongkhach.setText(_translate("MainWindow", "Thống kê lượng khách"))
