# Form implementation generated from reading ui file 'StatisticMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1037, 746)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidgetKhachhang = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidgetKhachhang.setGeometry(QtCore.QRect(0, 130, 1011, 561))
        self.tabWidgetKhachhang.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"font-weight: Bold")
        self.tabWidgetKhachhang.setObjectName("tabWidgetKhachhang")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(parent=self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 9, 926, 502))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.layoutWidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 500))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(parent=self.widget)
        self.groupBox.setMinimumSize(QtCore.QSize(550, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayoutChart = QtWidgets.QVBoxLayout()
        self.verticalLayoutChart.setObjectName("verticalLayoutChart")
        self.verticalLayout_8.addLayout(self.verticalLayoutChart)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.pushButtonTKgoitap = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButtonTKgoitap.setMinimumSize(QtCore.QSize(270, 50))
        self.pushButtonTKgoitap.setMaximumSize(QtCore.QSize(270, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        self.pushButtonTKgoitap.setFont(font)
        self.pushButtonTKgoitap.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonTKgoitap.setStyleSheet("\n"
"/* Trạng thái bình thường (Code gốc của mày) */\n"
"QPushButton {\n"
"   background-color: rgb(203, 221, 209);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;\n"
"font-weight: Bold;\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) - Đảo màu cho xịn */\n"
"QPushButton:hover {\n"
"    background-color: #1a6b61; /* Nền biến thành xanh đậm */\n"
"    color: #f6f6e9; /* Chữ sáng lên */\n"
"    /* Viền giữ nguyên màu xanh đậm nên tao không cần viết lại ở đây */\n"
"}\n"
"\n"
"/* Trạng thái khi click chuột bấm xuống (Pressed) */\n"
"QPushButton:pressed {\n"
"    background-color: #0a2e2a; /* Nền tối hơn một tông so với lúc hover */\n"
"    border: 3px solid #0a2e2a; /* Viền cũng tối theo */\n"
"    color: #f6f6e9;\n"
"}")
        self.pushButtonTKgoitap.setObjectName("pushButtonTKgoitap")
        self.verticalLayout_5.addWidget(self.pushButtonTKgoitap)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.pushButtonTKdoanhthu = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButtonTKdoanhthu.setMinimumSize(QtCore.QSize(270, 50))
        self.pushButtonTKdoanhthu.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        self.pushButtonTKdoanhthu.setFont(font)
        self.pushButtonTKdoanhthu.setStyleSheet("\n"
"/* Trạng thái bình thường (Code gốc của mày) */\n"
"QPushButton {\n"
"background-color: rgb(165, 185, 172);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;\n"
"font-weight: Bold;\n"
"\n"
"\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) - Đảo màu cho xịn */\n"
"QPushButton:hover {\n"
"    background-color: #1a6b61; /* Nền biến thành xanh đậm */\n"
"    color: #f6f6e9; /* Chữ sáng lên */\n"
"    /* Viền giữ nguyên màu xanh đậm nên tao không cần viết lại ở đây */\n"
"}\n"
"\n"
"/* Trạng thái khi click chuột bấm xuống (Pressed) */\n"
"QPushButton:pressed {\n"
"    background-color: #0a2e2a; /* Nền tối hơn một tông so với lúc hover */\n"
"    border: 3px solid #0a2e2a; /* Viền cũng tối theo */\n"
"    color: #f6f6e9;\n"
"}")
        self.pushButtonTKdoanhthu.setObjectName("pushButtonTKdoanhthu")
        self.verticalLayout_5.addWidget(self.pushButtonTKdoanhthu)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.pushButtonTKluongkhach = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButtonTKluongkhach.setMinimumSize(QtCore.QSize(270, 50))
        self.pushButtonTKluongkhach.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        self.pushButtonTKluongkhach.setFont(font)
        self.pushButtonTKluongkhach.setStyleSheet("\n"
"\n"
"/* Trạng thái bình thường (Code gốc của mày) */\n"
"QPushButton {\n"
"background-color: rgb(203, 221, 209);\n"
"border-radius: 15px;\n"
"border: 3px solid  #58827d;\n"
"font-weight: Bold\n"
"\n"
"\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) - Đảo màu cho xịn */\n"
"QPushButton:hover {\n"
"    background-color: #1a6b61; /* Nền biến thành xanh đậm */\n"
"    color: #f6f6e9; /* Chữ sáng lên */\n"
"    /* Viền giữ nguyên màu xanh đậm nên tao không cần viết lại ở đây */\n"
"}\n"
"\n"
"/* Trạng thái khi click chuột bấm xuống (Pressed) */\n"
"QPushButton:pressed {\n"
"    background-color: #0a2e2a; /* Nền tối hơn một tông so với lúc hover */\n"
"    border: 3px solid #0a2e2a; /* Viền cũng tối theo */\n"
"    color: #f6f6e9;\n"
"}")
        self.pushButtonTKluongkhach.setObjectName("pushButtonTKluongkhach")
        self.verticalLayout_5.addWidget(self.pushButtonTKluongkhach)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.widget)
        self.tabWidgetKhachhang.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_2.addLayout(self.horizontalLayout_5)
        self.tableWidgetPt = QtWidgets.QTableWidget(parent=self.tab_2)
        self.tableWidgetPt.setMinimumSize(QtCore.QSize(525, 0))
        self.tableWidgetPt.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.tableWidgetPt.setObjectName("tableWidgetPt")
        self.tableWidgetPt.setColumnCount(7)
        self.tableWidgetPt.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPt.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPt.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPt.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPt.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPt.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPt.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPt.setHorizontalHeaderItem(6, item)
        self.horizontalLayout_2.addWidget(self.tableWidgetPt)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_4 = QtWidgets.QWidget(parent=self.tab_2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_3 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.widget_3)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditEmailPt = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditEmailPt.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.lineEditEmailPt.setObjectName("lineEditEmailPt")
        self.gridLayout.addWidget(self.lineEditEmailPt, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButtonMale = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButtonMale.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.radioButtonMale.setObjectName("radioButtonMale")
        self.horizontalLayout_8.addWidget(self.radioButtonMale)
        self.radioButtonFemale = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButtonFemale.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.radioButtonFemale.setObjectName("radioButtonFemale")
        self.horizontalLayout_8.addWidget(self.radioButtonFemale)
        self.gridLayout.addLayout(self.horizontalLayout_8, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEditPhonePt = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditPhonePt.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.lineEditPhonePt.setObjectName("lineEditPhonePt")
        self.gridLayout.addWidget(self.lineEditPhonePt, 2, 1, 1, 1)
        self.lineEditRolePt = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditRolePt.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.lineEditRolePt.setObjectName("lineEditRolePt")
        self.gridLayout.addWidget(self.lineEditRolePt, 4, 1, 1, 1)
        self.lineEditNamePt = QtWidgets.QLineEdit(parent=self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.lineEditNamePt.setFont(font)
        self.lineEditNamePt.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.lineEditNamePt.setObjectName("lineEditNamePt")
        self.gridLayout.addWidget(self.lineEditNamePt, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEditDatePt = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditDatePt.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.lineEditDatePt.setObjectName("lineEditDatePt")
        self.gridLayout.addWidget(self.lineEditDatePt, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_6.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_7.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.lineEditTimePt = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditTimePt.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.lineEditTimePt.setObjectName("lineEditTimePt")
        self.gridLayout.addWidget(self.lineEditTimePt, 6, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_8.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.verticalLayout_11.addWidget(self.widget_3)
        self.verticalLayout_10.addLayout(self.verticalLayout_11)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButtonAdd = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButtonAdd.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pushButtonAdd.setStyleSheet("/* Trạng thái bình thường (Code gốc của mày) */\n"
"QPushButton {\n"
"    color: #0f433d;\n"
"    background-color: #f6f6e9;\n"
"    font: 87 20pt \"Noto Sans HK Black\";\n"
"    border-radius: 15px;\n"
"    border: 3px solid #0f433d;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) - Đảo màu cho xịn */\n"
"QPushButton:hover {\n"
"    background-color: #1a6b61; /* Nền biến thành xanh đậm */\n"
"    color: #f6f6e9; /* Chữ sáng lên */\n"
"    /* Viền giữ nguyên màu xanh đậm nên tao không cần viết lại ở đây */\n"
"}\n"
"\n"
"/* Trạng thái khi click chuột bấm xuống (Pressed) */\n"
"QPushButton:pressed {\n"
"    background-color: #0a2e2a; /* Nền tối hơn một tông so với lúc hover */\n"
"    border: 3px solid #0a2e2a; /* Viền cũng tối theo */\n"
"    color: #f6f6e9;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../images/plus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonAdd.setIcon(icon)
        self.pushButtonAdd.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.gridLayout_4.addWidget(self.pushButtonAdd, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButtonDelete = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButtonDelete.setStyleSheet("/* Trạng thái bình thường (Code gốc của mày) */\n"
"QPushButton {\n"
"    color: #0f433d;\n"
"    background-color: #f6f6e9;\n"
"    font: 87 20pt \"Noto Sans HK Black\";\n"
"    border-radius: 15px;\n"
"    border: 3px solid #0f433d;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) - Đảo màu cho xịn */\n"
"QPushButton:hover {\n"
"    background-color: #1a6b61; /* Nền biến thành xanh đậm */\n"
"    color: #f6f6e9; /* Chữ sáng lên */\n"
"    /* Viền giữ nguyên màu xanh đậm nên tao không cần viết lại ở đây */\n"
"}\n"
"\n"
"/* Trạng thái khi click chuột bấm xuống (Pressed) */\n"
"QPushButton:pressed {\n"
"    background-color: #0a2e2a; /* Nền tối hơn một tông so với lúc hover */\n"
"    border: 3px solid #0a2e2a; /* Viền cũng tối theo */\n"
"    color: #f6f6e9;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../images/remove.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonDelete.setIcon(icon1)
        self.pushButtonDelete.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.gridLayout_3.addWidget(self.pushButtonDelete, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 1, 1, 1)
        self.pushButtonSave = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButtonSave.setStyleSheet("QPushButton{color:rgb(255, 255, 255);\n"
"background-color:#97b690;\n"
"font: 87 20pt \"Noto Sans HK Black\";\n"
"border-radius: 15px;\n"
"border: 3px solid  #0f433d;\n"
"font-weight:bold;}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) - Đảo màu cho xịn */\n"
"QPushButton:hover {\n"
"    background-color: #1a6b61; /* Nền biến thành xanh đậm */\n"
"    color: #f6f6e9; /* Chữ sáng lên */\n"
"    /* Viền giữ nguyên màu xanh đậm nên tao không cần viết lại ở đây */\n"
"}\n"
"\n"
"/* Trạng thái khi click chuột bấm xuống (Pressed) */\n"
"QPushButton:pressed {\n"
"    background-color: #0a2e2a; /* Nền tối hơn một tông so với lúc hover */\n"
"    border: 3px solid #0a2e2a; /* Viền cũng tối theo */\n"
"    color: #f6f6e9;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../images/diskette.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSave.setIcon(icon2)
        self.pushButtonSave.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.gridLayout_4.addWidget(self.pushButtonSave, 1, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.widget_5)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.horizontalLayout.addWidget(self.widget_4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidgetKhachhang.addTab(self.tab_2, "")
        self.widget1 = QtWidgets.QWidget()
        self.widget1.setObjectName("widget1")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.widget1)
        self.tableWidget.setMaximumSize(QtCore.QSize(1500, 1500))
        self.tableWidget.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_9.addWidget(self.tableWidget)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButtonTudo = QtWidgets.QPushButton(parent=self.widget1)
        self.pushButtonTudo.setMinimumSize(QtCore.QSize(400, 0))
        self.pushButtonTudo.setMaximumSize(QtCore.QSize(500, 60))
        self.pushButtonTudo.setStyleSheet("QPushButton{color:rgb(255, 255, 255);\n"
"background-color:#97b690;\n"
"font: 87 20pt \"Noto Sans HK Black\";\n"
"border-radius: 15px;\n"
"border: 3px solid  #0f433d;\n"
"font-weight:bold;}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) - Đảo màu cho xịn */\n"
"QPushButton:hover {\n"
"    background-color: #1a6b61; /* Nền biến thành xanh đậm */\n"
"    color: #f6f6e9; /* Chữ sáng lên */\n"
"    /* Viền giữ nguyên màu xanh đậm nên tao không cần viết lại ở đây */\n"
"}\n"
"\n"
"/* Trạng thái khi click chuột bấm xuống (Pressed) */\n"
"QPushButton:pressed {\n"
"    background-color: #0a2e2a; /* Nền tối hơn một tông so với lúc hover */\n"
"    border: 3px solid #0a2e2a; /* Viền cũng tối theo */\n"
"    color: #f6f6e9;\n"
"}")
        self.pushButtonTudo.setObjectName("pushButtonTudo")
        self.verticalLayout_2.addWidget(self.pushButtonTudo)
        self.pushButtonBoxing = QtWidgets.QPushButton(parent=self.widget1)
        self.pushButtonBoxing.setMaximumSize(QtCore.QSize(500, 60))
        self.pushButtonBoxing.setStyleSheet("/* Trạng thái bình thường (Code gốc của mày) */\n"
"QPushButton {\n"
"    color: #0f433d;\n"
"    background-color: #f6f6e9;\n"
"    font: 87 20pt \"Noto Sans HK Black\";\n"
"    border-radius: 15px;\n"
"    border: 3px solid #0f433d;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) - Đảo màu cho xịn */\n"
"QPushButton:hover {\n"
"    background-color: #1a6b61; /* Nền biến thành xanh đậm */\n"
"    color: #f6f6e9; /* Chữ sáng lên */\n"
"    /* Viền giữ nguyên màu xanh đậm nên tao không cần viết lại ở đây */\n"
"}\n"
"\n"
"/* Trạng thái khi click chuột bấm xuống (Pressed) */\n"
"QPushButton:pressed {\n"
"    background-color: #0a2e2a; /* Nền tối hơn một tông so với lúc hover */\n"
"    border: 3px solid #0a2e2a; /* Viền cũng tối theo */\n"
"    color: #f6f6e9;\n"
"}")
        self.pushButtonBoxing.setObjectName("pushButtonBoxing")
        self.verticalLayout_2.addWidget(self.pushButtonBoxing)
        self.pushButtonPilates = QtWidgets.QPushButton(parent=self.widget1)
        self.pushButtonPilates.setMaximumSize(QtCore.QSize(500, 60))
        self.pushButtonPilates.setStyleSheet("QPushButton{color:rgb(255, 255, 255);\n"
"background-color:#97b690;\n"
"font: 87 20pt \"Noto Sans HK Black\";\n"
"border-radius: 15px;\n"
"border: 3px solid  #0f433d;\n"
"font-weight:bold;}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) - Đảo màu cho xịn */\n"
"QPushButton:hover {\n"
"    background-color: #1a6b61; /* Nền biến thành xanh đậm */\n"
"    color: #f6f6e9; /* Chữ sáng lên */\n"
"    /* Viền giữ nguyên màu xanh đậm nên tao không cần viết lại ở đây */\n"
"}\n"
"\n"
"/* Trạng thái khi click chuột bấm xuống (Pressed) */\n"
"QPushButton:pressed {\n"
"    background-color: #0a2e2a; /* Nền tối hơn một tông so với lúc hover */\n"
"    border: 3px solid #0a2e2a; /* Viền cũng tối theo */\n"
"    color: #f6f6e9;\n"
"}")
        self.pushButtonPilates.setObjectName("pushButtonPilates")
        self.verticalLayout_2.addWidget(self.pushButtonPilates)
        self.pushButtonYoga = QtWidgets.QPushButton(parent=self.widget1)
        self.pushButtonYoga.setMaximumSize(QtCore.QSize(500, 60))
        self.pushButtonYoga.setStyleSheet("/* Trạng thái bình thường (Code gốc của mày) */\n"
"QPushButton {\n"
"    color: #0f433d;\n"
"    background-color: #f6f6e9;\n"
"    font: 87 20pt \"Noto Sans HK Black\";\n"
"    border-radius: 15px;\n"
"    border: 3px solid #0f433d;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) - Đảo màu cho xịn */\n"
"QPushButton:hover {\n"
"    background-color: #1a6b61; /* Nền biến thành xanh đậm */\n"
"    color: #f6f6e9; /* Chữ sáng lên */\n"
"    /* Viền giữ nguyên màu xanh đậm nên tao không cần viết lại ở đây */\n"
"}\n"
"\n"
"/* Trạng thái khi click chuột bấm xuống (Pressed) */\n"
"QPushButton:pressed {\n"
"    background-color: #0a2e2a; /* Nền tối hơn một tông so với lúc hover */\n"
"    border: 3px solid #0a2e2a; /* Viền cũng tối theo */\n"
"    color: #f6f6e9;\n"
"}")
        self.pushButtonYoga.setObjectName("pushButtonYoga")
        self.verticalLayout_2.addWidget(self.pushButtonYoga)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.tabWidgetKhachhang.addTab(self.widget1, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1037, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidgetKhachhang.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonTKgoitap.setText(_translate("MainWindow", "Thống kê gói tập"))
        self.pushButtonTKdoanhthu.setText(_translate("MainWindow", "Thống kê doanh thu"))
        self.pushButtonTKluongkhach.setText(_translate("MainWindow", "Thống kê lượng khách"))
        self.tabWidgetKhachhang.setTabText(self.tabWidgetKhachhang.indexOf(self.tab), _translate("MainWindow", "BẢNG THỐNG KÊ"))
        item = self.tableWidgetPt.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Họ và tên"))
        item = self.tableWidgetPt.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "SĐT"))
        item = self.tableWidgetPt.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidgetPt.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Giới tính"))
        item = self.tableWidgetPt.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Lĩnh Vực"))
        item = self.tableWidgetPt.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Ngày hoạt động"))
        item = self.tableWidgetPt.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Giờ hoạt động"))
        self.label_4.setText(_translate("MainWindow", "Email:"))
        self.radioButtonMale.setText(_translate("MainWindow", "Male"))
        self.radioButtonFemale.setText(_translate("MainWindow", "Female"))
        self.label.setText(_translate("MainWindow", "Họ và tên:"))
        self.label_3.setText(_translate("MainWindow", "SĐT:"))
        self.label_5.setText(_translate("MainWindow", "Giới tính:"))
        self.label_6.setText(_translate("MainWindow", "Lĩnh vực:"))
        self.label_7.setText(_translate("MainWindow", "Ngày hoạt động:"))
        self.label_8.setText(_translate("MainWindow", "Giờ hoạt động:"))
        self.pushButtonAdd.setText(_translate("MainWindow", "Add"))
        self.pushButtonDelete.setText(_translate("MainWindow", "Remove"))
        self.pushButtonSave.setText(_translate("MainWindow", "Save"))
        self.tabWidgetKhachhang.setTabText(self.tabWidgetKhachhang.indexOf(self.tab_2), _translate("MainWindow", "DANH SÁCH HUẤN LUYỆN VIÊN"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Họ và tên"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "SĐT"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Môn đăng ký"))
        self.pushButtonTudo.setText(_translate("MainWindow", "Tự do"))
        self.pushButtonBoxing.setText(_translate("MainWindow", "Boxing"))
        self.pushButtonPilates.setText(_translate("MainWindow", "Pilates"))
        self.pushButtonYoga.setText(_translate("MainWindow", "Yoga"))
        self.tabWidgetKhachhang.setTabText(self.tabWidgetKhachhang.indexOf(self.widget1), _translate("MainWindow", "DANH SÁCH KHÁCH HÀNG"))
