# Form implementation generated from reading ui file 'D:\Nam1\KTLT\DoAn\ui\registration\Registration_formMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1884, 908)
        MainWindow.setStyleSheet("QMainWindow{\n"
"border-image:url(:/pic/Registration.png);\n"
"background-iamge:rgb(0,255,255);}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonBathang = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBathang.setGeometry(QtCore.QRect(640, 530, 321, 79))
        self.pushButtonBathang.setMaximumSize(QtCore.QSize(900, 80))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonBathang.setFont(font)
        self.pushButtonBathang.setStyleSheet("color:#0f433d;\n"
"background-color: #f6f6e9;\n"
"font: 22pt \"MS Shell Dlg 2\";\n"
"border-radius: 20px;\n"
"border: 3px solid  #0f433d;")
        self.pushButtonBathang.setObjectName("pushButtonBathang")
        self.pushButtonSauthang = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSauthang.setGeometry(QtCore.QRect(640, 640, 321, 79))
        self.pushButtonSauthang.setMaximumSize(QtCore.QSize(900, 80))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonSauthang.setFont(font)
        self.pushButtonSauthang.setStyleSheet("color:#0f433d;\n"
"background-color: #f6f6e9;\n"
"font: 22pt \"MS Shell Dlg 2\";\n"
"border-radius: 20px;\n"
"border: 3px solid  #0f433d;")
        self.pushButtonSauthang.setObjectName("pushButtonSauthang")
        self.pushButtonMotnam = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMotnam.setGeometry(QtCore.QRect(1150, 420, 311, 79))
        self.pushButtonMotnam.setMaximumSize(QtCore.QSize(900, 80))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonMotnam.setFont(font)
        self.pushButtonMotnam.setStyleSheet("color:#0f433d;\n"
"background-color: #f6f6e9;\n"
"font: 22pt \"MS Shell Dlg 2\";\n"
"border-radius: 20px;\n"
"border: 3px solid  #0f433d;")
        self.pushButtonMotnam.setObjectName("pushButtonMotnam")
        self.pushButtonMotthang = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMotthang.setGeometry(QtCore.QRect(640, 420, 321, 80))
        self.pushButtonMotthang.setMaximumSize(QtCore.QSize(900, 80))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonMotthang.setFont(font)
        self.pushButtonMotthang.setStyleSheet("color:#0f433d;\n"
"background-color: #f6f6e9;\n"
"font: 22pt \"MS Shell Dlg 2\";\n"
"border-radius: 20px;\n"
"border: 3px solid  #0f433d;")
        self.pushButtonMotthang.setObjectName("pushButtonMotthang")
        self.pushButtonHaituan = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonHaituan.setGeometry(QtCore.QRect(130, 410, 321, 80))
        self.pushButtonHaituan.setMaximumSize(QtCore.QSize(900, 80))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonHaituan.setFont(font)
        self.pushButtonHaituan.setStyleSheet("color:#0f433d;\n"
"background-color: #f6f6e9;\n"
"font: 22pt \"MS Shell Dlg 2\";\n"
"border-radius: 20px;\n"
"border: 3px solid  #0f433d;")
        self.pushButtonHaituan.setObjectName("pushButtonHaituan")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1884, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonBathang.setText(_translate("MainWindow", "3 tháng: 1.399K"))
        self.pushButtonSauthang.setText(_translate("MainWindow", "6 tháng: 2.499K"))
        self.pushButtonMotnam.setText(_translate("MainWindow", "1 năm: 4.799K"))
        self.pushButtonMotthang.setText(_translate("MainWindow", "1 tháng: 499K"))
        self.pushButtonHaituan.setText(_translate("MainWindow", "2 tuần: 299K"))
