# Form implementation generated from reading ui file 'Registration_formMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1884, 908)
        MainWindow.setStyleSheet("QMainWindow{\n"
"border-image:url(:/pic/Registration.png);\n"
"background-iamge:rgb(0,255,255);}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonBathang = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBathang.setGeometry(QtCore.QRect(640, 530, 321, 79))
        self.pushButtonBathang.setMaximumSize(QtCore.QSize(900, 80))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        self.pushButtonBathang.setFont(font)
        self.pushButtonBathang.setStyleSheet("/* Trạng thái bình thường */\n"
"QPushButton {\n"
"    color: #0f433d;\n"
"    background-color: #f6f6e9;\n"
"    font: 22pt \"MS Shell Dlg 2\";\n"
"    border-radius: 20px;\n"
"    border: 3px solid #0f433d;\n"
"}\n"
"\n"
"/* Khi rê chuột vào (Hover) - Vàng trầm nhưng nhạt và dịu hơn */\n"
"QPushButton:hover {\n"
"    background-color: #e0c975; \n"
"    color: #0f433d;\n"
"}\n"
"\n"
"/* Khi click chuột (Pressed) - Đậm hơn lúc hover một xíu + lún nút */\n"
"QPushButton:pressed {\n"
"    background-color: #ccb258; \n"
"    padding-top: 4px;\n"
"    padding-left: 4px;\n"
"}")
        self.pushButtonBathang.setObjectName("pushButtonBathang")
        self.pushButtonSauthang = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSauthang.setGeometry(QtCore.QRect(640, 640, 321, 79))
        self.pushButtonSauthang.setMaximumSize(QtCore.QSize(900, 80))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        self.pushButtonSauthang.setFont(font)
        self.pushButtonSauthang.setStyleSheet("/* Trạng thái bình thường */\n"
"QPushButton {\n"
"    color: #0f433d;\n"
"    background-color: #f6f6e9;\n"
"    font: 22pt \"MS Shell Dlg 2\";\n"
"    border-radius: 20px;\n"
"    border: 3px solid #0f433d;\n"
"}\n"
"\n"
"/* Khi rê chuột vào (Hover) - Vàng trầm nhưng nhạt và dịu hơn */\n"
"QPushButton:hover {\n"
"    background-color: #e0c975; \n"
"    color: #0f433d;\n"
"}\n"
"\n"
"/* Khi click chuột (Pressed) - Đậm hơn lúc hover một xíu + lún nút */\n"
"QPushButton:pressed {\n"
"    background-color: #ccb258; \n"
"    padding-top: 4px;\n"
"    padding-left: 4px;\n"
"}")
        self.pushButtonSauthang.setObjectName("pushButtonSauthang")
        self.pushButtonMotnam = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMotnam.setGeometry(QtCore.QRect(1150, 420, 311, 79))
        self.pushButtonMotnam.setMaximumSize(QtCore.QSize(900, 80))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        self.pushButtonMotnam.setFont(font)
        self.pushButtonMotnam.setStyleSheet("/* Trạng thái bình thường */\n"
"QPushButton {\n"
"    color: #0f433d;\n"
"    background-color: #f6f6e9;\n"
"    font: 22pt \"MS Shell Dlg 2\";\n"
"    border-radius: 20px;\n"
"    border: 3px solid #0f433d;\n"
"}\n"
"\n"
"/* Khi rê chuột vào (Hover) - Vàng trầm nhưng nhạt và dịu hơn */\n"
"QPushButton:hover {\n"
"    background-color: #e0c975; \n"
"    color: #0f433d;\n"
"}\n"
"\n"
"/* Khi click chuột (Pressed) - Đậm hơn lúc hover một xíu + lún nút */\n"
"QPushButton:pressed {\n"
"    background-color: #ccb258; \n"
"    padding-top: 4px;\n"
"    padding-left: 4px;\n"
"}")
        self.pushButtonMotnam.setObjectName("pushButtonMotnam")
        self.pushButtonMotthang = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMotthang.setGeometry(QtCore.QRect(640, 420, 321, 80))
        self.pushButtonMotthang.setMaximumSize(QtCore.QSize(900, 80))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        self.pushButtonMotthang.setFont(font)
        self.pushButtonMotthang.setStyleSheet("/* Trạng thái bình thường */\n"
"QPushButton {\n"
"    color: #0f433d;\n"
"    background-color: #f6f6e9;\n"
"    font: 22pt \"MS Shell Dlg 2\";\n"
"    border-radius: 20px;\n"
"    border: 3px solid #0f433d;\n"
"}\n"
"\n"
"/* Khi rê chuột vào (Hover) - Vàng trầm nhưng nhạt và dịu hơn */\n"
"QPushButton:hover {\n"
"    background-color: #e0c975; \n"
"    color: #0f433d;\n"
"}\n"
"\n"
"/* Khi click chuột (Pressed) - Đậm hơn lúc hover một xíu + lún nút */\n"
"QPushButton:pressed {\n"
"    background-color: #ccb258; \n"
"    padding-top: 4px;\n"
"    padding-left: 4px;\n"
"}")
        self.pushButtonMotthang.setObjectName("pushButtonMotthang")
        self.pushButtonHaituan = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonHaituan.setGeometry(QtCore.QRect(130, 410, 321, 80))
        self.pushButtonHaituan.setMaximumSize(QtCore.QSize(900, 80))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        self.pushButtonHaituan.setFont(font)
        self.pushButtonHaituan.setStyleSheet("/* Trạng thái bình thường */\n"
"QPushButton {\n"
"    color: #0f433d;\n"
"    background-color: #f6f6e9;\n"
"    font: 22pt \"MS Shell Dlg 2\";\n"
"    border-radius: 20px;\n"
"    border: 3px solid #0f433d;\n"
"}\n"
"\n"
"/* Khi rê chuột vào (Hover) - Vàng trầm nhưng nhạt và dịu hơn */\n"
"QPushButton:hover {\n"
"    background-color: #e0c975; \n"
"    color: #0f433d;\n"
"}\n"
"\n"
"/* Khi click chuột (Pressed) - Đậm hơn lúc hover một xíu + lún nút */\n"
"QPushButton:pressed {\n"
"    background-color: #ccb258; \n"
"    padding-top: 4px;\n"
"    padding-left: 4px;\n"
"}")
        self.pushButtonHaituan.setObjectName("pushButtonHaituan")
        self.pushButtonback = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonback.setGeometry(QtCore.QRect(1200, 50, 241, 61))
        self.pushButtonback.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Sans HK Black")
        font.setPointSize(20)
        font.setItalic(False)
        self.pushButtonback.setFont(font)
        self.pushButtonback.setStyleSheet("/* Trạng thái bình thường (Giữ nguyên 100% của mày) */\n"
"QPushButton {\n"
"    color: #f6f6e9;\n"
"    background-color: #0f433d;\n"
"    font: 87 20pt \"Noto Sans HK Black\";\n"
"    border-radius: 30px;\n"
"    border: 3px solid #58827d;\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) */\n"
"QPushButton:hover {\n"
"    background-color: #1a6b61; /* Màu xanh sáng hơn một chút để nổi bật */\n"
"    border: 3px solid #73a6a0; /* Viền cũng sáng lên một chút cho đồng bộ */\n"
"}\n"
"\n"
"/* Thêm luôn trạng thái khi click (bấm xuống) cho nó xịn */\n"
"QPushButton:pressed {\n"
"    background-color: #0a2e2a; /* Nền tối đi khi bấm */\n"
"    border: 3px solid #3d5e5b; /* Viền tối đi */\n"
"}")
        self.pushButtonback.setObjectName("pushButtonback")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1884, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonBathang.setText(_translate("MainWindow", "3 tháng: 1.399K"))
        self.pushButtonSauthang.setText(_translate("MainWindow", "6 tháng: 2.499K"))
        self.pushButtonMotnam.setText(_translate("MainWindow", "1 năm: 4.799K"))
        self.pushButtonMotthang.setText(_translate("MainWindow", "1 tháng: 499K"))
        self.pushButtonHaituan.setText(_translate("MainWindow", "2 tuần: 299K"))
        self.pushButtonback.setText(_translate("MainWindow", "Back"))
