# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 376)
        MainWindow.setStyleSheet("#centralwidget{\n"
"border-image: url(D:/Nam_1/K25411_KTLT/project/images/login.png);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.frame_4.setStyleSheet("QFrame {\n"
"    border-radius: 30px;\n"
"    background-color: rgb(248, 255, 212);\n"
"layoutRow = 0\n"
"layoutColumn = 0\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setLineWidth(2)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(6, -1, -1, -1)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout_17.setHorizontalSpacing(5)
        self.gridLayout_17.setVerticalSpacing(10)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.pushButtonSignUp = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSignUp.sizePolicy().hasHeightForWidth())
        self.pushButtonSignUp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonSignUp.setFont(font)
        self.pushButtonSignUp.setStyleSheet("QPushButton{\n"
"border:none;\n"
"color:#1a73e8;\n"
"background:transparent;\n"
"}\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"}")
        self.pushButtonSignUp.setObjectName("pushButtonSignUp")
        self.gridLayout_17.addWidget(self.pushButtonSignUp, 2, 3, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.radioButtonUser = QtWidgets.QRadioButton(parent=self.frame_4)
        self.radioButtonUser.setObjectName("radioButtonUser")
        self.gridLayout_17.addWidget(self.radioButtonUser, 2, 2, 1, 1)
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPassword.sizePolicy().hasHeightForWidth())
        self.lineEditPassword.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditPassword.setFont(font)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.gridLayout_17.addWidget(self.lineEditPassword, 1, 0, 1, 4)
        self.lineEditUsername = QtWidgets.QLineEdit(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditUsername.sizePolicy().hasHeightForWidth())
        self.lineEditUsername.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditUsername.setFont(font)
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.gridLayout_17.addWidget(self.lineEditUsername, 0, 0, 1, 4)
        self.radioButtonAdmin = QtWidgets.QRadioButton(parent=self.frame_4)
        self.radioButtonAdmin.setObjectName("radioButtonAdmin")
        self.gridLayout_17.addWidget(self.radioButtonAdmin, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_17.addWidget(self.label_2, 2, 0, 1, 1)
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLogin.sizePolicy().hasHeightForWidth())
        self.pushButtonLogin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.pushButtonLogin.setFont(font)
        self.pushButtonLogin.setStyleSheet("/* Trạng thái mặc định (CÓ VIỀN MẢNH) */\n"
"QPushButton#pushButtonLogin {\n"
"    background-color: rgb(11, 143, 119); /* Giữ màu xanh chuẩn của mày */\n"
"    color: white;\n"
"    border-radius: 15px; /* Bo góc viên thuốc */\n"
"    padding: 5px;\n"
"    \n"
"    /* 👇 PHẦN THÊM VIỀN NẰM Ở ĐÂY 👇 */\n"
"    border: 2px solid rgba(255, 255, 255, 100); /* Viền trắng mảnh, độ mờ 100 */\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) */\n"
"QPushButton#pushButtonLogin:hover {\n"
"    background-color: rgb(8, 115, 95); /* Màu đậm hơn khi hover */\n"
"    \n"
"    /* Thay đổi viền khi hover để nút nổi bật hơn */\n"
"    border: 2px solid rgba(255, 255, 255, 180); /* Viền trắng sáng hơn */\n"
"}")
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.gridLayout_17.addWidget(self.pushButtonLogin, 3, 0, 1, 4)
        self.pushButtonForgetPassword = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonForgetPassword.sizePolicy().hasHeightForWidth())
        self.pushButtonForgetPassword.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonForgetPassword.setFont(font)
        self.pushButtonForgetPassword.setStyleSheet("QPushButton{\n"
"border:none;\n"
"color:#1a73e8;\n"
"background:transparent;\n"
"}\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"}")
        self.pushButtonForgetPassword.setObjectName("pushButtonForgetPassword")
        self.gridLayout_17.addWidget(self.pushButtonForgetPassword, 4, 0, 1, 4)
        self.gridLayout_17.setRowStretch(0, 2)
        self.verticalLayout_4.addLayout(self.gridLayout_17)
        self.gridLayout.addWidget(self.frame_4, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 5)
        self.gridLayout.setColumnStretch(2, 2)
        self.gridLayout.setRowStretch(0, 3)
        self.gridLayout.setRowStretch(1, 6)
        self.gridLayout.setRowStretch(2, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonSignUp.setText(_translate("MainWindow", "Sign up?"))
        self.radioButtonUser.setText(_translate("MainWindow", "User"))
        self.lineEditPassword.setPlaceholderText(_translate("MainWindow", "Password"))
        self.lineEditUsername.setPlaceholderText(_translate("MainWindow", "Username"))
        self.radioButtonAdmin.setText(_translate("MainWindow", "Admin"))
        self.label_2.setText(_translate("MainWindow", "Login as:"))
        self.pushButtonLogin.setText(_translate("MainWindow", "Login"))
        self.pushButtonForgetPassword.setText(_translate("MainWindow", "Forget password"))
