# Form implementation generated from reading ui file 'Dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1363, 664)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("QMainWindow{\n"
"border-image:url(:/pic/Dashboard.png);\n"
"background-image:rgb(0,255,255);}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonAdmin = QtWidgets.QPushButton(parent=self.centralwidget)

        self.pushButtonAdmin.setMinimumSize(QtCore.QSize(170, 70))
        self.pushButtonAdmin.setStyleSheet("/* Trạng thái bình thường (Code gốc của mày) */\n"
"QPushButton {\n"
"    color: #0f433d;\n"
"    background-color: #f6f6e9;\n"
"    font: 87 20pt \"Noto Sans HK Black\";\n"
"    border-radius: 30px;\n"
"    border: 3px solid #0f433d;\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) - Đảo màu cho xịn */\n"
"QPushButton:hover {\n"
"    background-color: #1a6b61; /* Nền biến thành xanh đậm */\n"
"    color: #f6f6e9; /* Chữ sáng lên */\n"
"    /* Viền giữ nguyên màu xanh đậm nên tao không cần viết lại ở đây */\n"
"}\n"
"\n"
"/* Trạng thái khi click chuột bấm xuống (Pressed) */\n"
"QPushButton:pressed {\n"
"    background-color: #0a2e2a; /* Nền tối hơn một tông so với lúc hover */\n"
"    border: 3px solid #0a2e2a; /* Viền cũng tối theo */\n"
"    color: #f6f6e9;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/manager.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonAdmin.setIcon(icon)
        self.pushButtonAdmin.setIconSize(QtCore.QSize(50, 50))

        self.pushButtonAdmin.setMinimumSize(QtCore.QSize(100, 70))
        self.pushButtonAdmin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButtonAdmin.setStyleSheet("color:#0f433d;\n"
"background-color: #f6f6e9;\n"
"font: 87 15pt \"Noto Sans HK Black\";\n"
"border-radius: 30px;\n"
"border: 3px solid  #0f433d;")
        self.pushButtonAdmin.setIconSize(QtCore.QSize(30, 50))

        self.pushButtonAdmin.setObjectName("pushButtonAdmin")
        self.horizontalLayout.addWidget(self.pushButtonAdmin)
        self.pushButtonMember = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMember.setMinimumSize(QtCore.QSize(100, 70))
        self.pushButtonMember.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButtonMember.setStyleSheet("color:#0f433d;\n"
"background-color: rgb(165, 185, 172);\n"
"font: 87 15pt \"Noto Sans HK Black\";\n"
"border-radius: 30px;\n"
"border: 3px solid #f6f6e9;")
        self.pushButtonMember.setIconSize(QtCore.QSize(30, 50))
        self.pushButtonMember.setObjectName("pushButtonMember")
        self.horizontalLayout.addWidget(self.pushButtonMember)
        self.pushButtonLogOut = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLogOut.setMinimumSize(QtCore.QSize(100, 70))
        self.pushButtonLogOut.setMaximumSize(QtCore.QSize(16777215, 16777215))

        self.pushButtonLogOut.setStyleSheet("/* Trạng thái bình thường (Giữ nguyên 100% của mày) */\n"
"QPushButton {\n"
"    color: #f6f6e9;\n"
"    background-color: #0f433d;\n"
"    font: 87 20pt \"Noto Sans HK Black\";\n"
"    border-radius: 30px;\n"
"    border: 3px solid #58827d;\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) */\n"
"QPushButton:hover {\n"
"    background-color: #1a6b61; /* Màu xanh sáng hơn một chút để nổi bật */\n"
"    border: 3px solid #73a6a0; /* Viền cũng sáng lên một chút cho đồng bộ */\n"
"}\n"
"\n"
"/* Thêm luôn trạng thái khi click (bấm xuống) cho nó xịn */\n"
"QPushButton:pressed {\n"
"    background-color: #0a2e2a; /* Nền tối đi khi bấm */\n"
"    border: 3px solid #3d5e5b; /* Viền tối đi */\n"
"}")

        self.pushButtonLogOut.setStyleSheet("color:#f6f6e9;\n"
"background-color: #0f433d;\n"
"font: 87 15pt \"Noto Sans HK Black\";\n"
"border-radius: 30px;\n"
"border: 3px solid  #58827d;")

        self.pushButtonLogOut.setIconSize(QtCore.QSize(30, 50))
        self.pushButtonLogOut.setObjectName("pushButtonLogOut")
        self.horizontalLayout.addWidget(self.pushButtonLogOut)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonDkyHoivien = QtWidgets.QPushButton(parent=self.centralwidget)

        self.pushButtonDkyHoivien.setMinimumSize(QtCore.QSize(350, 70))
        self.pushButtonDkyHoivien.setStyleSheet("/* Trạng thái bình thường (Code gốc của mày) */\n"
"QPushButton {\n"
"    color: #0f433d;\n"
"    background-color: #f6f6e9;\n"
"    font: 87 20pt \"Noto Sans HK Black\";\n"
"    border-radius: 30px;\n"
"    border: 3px solid #0f433d;\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) - Đảo màu cho xịn */\n"
"QPushButton:hover {\n"
"    background-color: #1a6b61; /* Nền biến thành xanh đậm */\n"
"    color: #f6f6e9; /* Chữ sáng lên */\n"
"    /* Viền giữ nguyên màu xanh đậm nên tao không cần viết lại ở đây */\n"
"}\n"
"\n"
"/* Trạng thái khi click chuột bấm xuống (Pressed) */\n"
"QPushButton:pressed {\n"
"    background-color: #0a2e2a; /* Nền tối hơn một tông so với lúc hover */\n"
"    border: 3px solid #0a2e2a; /* Viền cũng tối theo */\n"
"    color: #f6f6e9;\n"
"}")

        self.pushButtonDkyHoivien.setMinimumSize(QtCore.QSize(300, 60))
        self.pushButtonDkyHoivien.setStyleSheet("color:#0f433d;\n"
"background-color: #f6f6e9;\n"
"font: 87 20pt \"Noto Sans HK Black\";\n"
"border-radius: 30px;\n"
"border: 3px solid  #0f433d;")

        self.pushButtonDkyHoivien.setObjectName("pushButtonDkyHoivien")
        self.gridLayout.addWidget(self.pushButtonDkyHoivien, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 6, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem8, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem9, 2, 1, 1, 1)
        self.pushButtonDatlich = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDatlich.setMinimumSize(QtCore.QSize(300, 60))
        self.pushButtonDatlich.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButtonDatlich.setStyleSheet("/* Trạng thái bình thường (Giữ nguyên 100% của mày) */\n"
"QPushButton {\n"
"    color: #f6f6e9;\n"
"    background-color: #0f433d;\n"
"    font: 87 20pt \"Noto Sans HK Black\";\n"
"    border-radius: 30px;\n"
"    border: 3px solid #58827d;\n"
"}\n"
"\n"
"/* Trạng thái khi rê chuột vào (Hover) */\n"
"QPushButton:hover {\n"
"    background-color: #1a6b61; /* Màu xanh sáng hơn một chút để nổi bật */\n"
"    border: 3px solid #73a6a0; /* Viền cũng sáng lên một chút cho đồng bộ */\n"
"}\n"
"\n"
"/* Thêm luôn trạng thái khi click (bấm xuống) cho nó xịn */\n"
"QPushButton:pressed {\n"
"    background-color: #0a2e2a; /* Nền tối đi khi bấm */\n"
"    border: 3px solid #3d5e5b; /* Viền tối đi */\n"
"}")
        self.pushButtonDatlich.setIconSize(QtCore.QSize(30, 50))
        self.pushButtonDatlich.setObjectName("pushButtonDatlich")
        self.gridLayout.addWidget(self.pushButtonDatlich, 1, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1363, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonAdmin.setText(_translate("MainWindow", "Admin"))
        self.pushButtonMember.setText(_translate("MainWindow", "Member"))
        self.pushButtonLogOut.setText(_translate("MainWindow", "Exit"))
        self.pushButtonDkyHoivien.setText(_translate("MainWindow", " Đăng ký hội viên"))
        self.pushButtonDatlich.setText(_translate("MainWindow", "Đặt lịch ngay"))
