# Form implementation generated from reading ui file 'NotiMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1208, 849)
        MainWindow.setStyleSheet("\n"
"#centralwidget {\n"
"    background-color: #f4f5eb;\n"
"    border-image: url(\"E:/MyFinalProject_BackgroundUi/images/thongbao_anh.jpg\"); \n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(490, 610, 261, 161))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #2d5a52;\n"
"    border-radius: 60px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setGeometry(QtCore.QRect(32, 30, 201, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    /* Màu kem bạn yêu cầu (lấy từ ảnh) */\n"
"    background-color: #f5f5dc; \n"
"    \n"
"    /* Bo tròn góc - chỉnh số này cho khớp với khung sau */\n"
"    border-radius: 40px; \n"
"    \n"
"    /* Viền nút (có thể để \'none\' nếu muốn nút phẳng lì) */\n"
"    border: 1px solid #dcdcdc; \n"
"    \n"
"    /* Chỉnh lề và font chữ nếu cần */\n"
"    padding: 5px;\n"
"    font-family: \"Segoe UI\";\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* Hiệu ứng khi di chuột vào cho đỡ bị đơ */\n"
"QPushButton:hover {\n"
"    background-color: #efefd0; /* Tối hơn một chút khi hover */\n"
"}\n"
"\n"
"/* Hiệu ứng khi click chuột */\n"
"QPushButton:pressed {\n"
"    background-color: #e5e5c0;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1208, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Đăng ký"))
