# Form implementation generated from reading ui file 'D:\Nam1\KTLT\DoAn\ui\member\MemberMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1253, 693)
        MainWindow.setStyleSheet("QMainWindow{\n"
"border-image:url(:/pic/hoivien_anh(update).jpg);\n"
"background-iamge:rgb(0,255,255);}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButtonKhonggiahan_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonKhonggiahan_2.setMinimumSize(QtCore.QSize(170, 50))
        self.pushButtonKhonggiahan_2.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButtonKhonggiahan_2.setStyleSheet("color:#0f433d;\n"
"background-color: #cbddd1;\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"border-radius: 20px;\n"
"border: 3px solid  #58827d;")
        self.pushButtonKhonggiahan_2.setIconSize(QtCore.QSize(30, 50))
        self.pushButtonKhonggiahan_2.setObjectName("pushButtonKhonggiahan_2")
        self.verticalLayout_7.addWidget(self.pushButtonKhonggiahan_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(500, 80))
        self.label.setStyleSheet("background-color:#cbddd1;\n"
"font: 87 18pt \"Noto Sans TC Black\";\n"
"border-radius: 20px;\n"
"border: 3px ;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(500, 300))
        self.groupBox.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color:#f6f6e9;\n"
"border-radius: 20px;\n"
"border: 3px ;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_2 = QtWidgets.QWidget(parent=self.groupBox)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lineEditName = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEditName.setStyleSheet("border-radius: 20px;\n"
"background-color: #cbddd1;\n"
"border: 3px solid  #0f433d;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.lineEditName.setObjectName("lineEditName")
        self.verticalLayout_10.addWidget(self.lineEditName)
        self.lineEditPhone = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEditPhone.setStyleSheet("border-radius: 20px;\n"
"border: 3px solid  #0f433d;\n"
"border-radius: 10px;")
        self.lineEditPhone.setObjectName("lineEditPhone")
        self.verticalLayout_10.addWidget(self.lineEditPhone)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.radioButtonMale = QtWidgets.QRadioButton(parent=self.widget_2)
        self.radioButtonMale.setObjectName("radioButtonMale")
        self.horizontalLayout_11.addWidget(self.radioButtonMale)
        self.radioButtonFemale = QtWidgets.QRadioButton(parent=self.widget_2)
        self.radioButtonFemale.setObjectName("radioButtonFemale")
        self.horizontalLayout_11.addWidget(self.radioButtonFemale)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.lineEditGoi = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEditGoi.setStyleSheet("border-radius: 20px;\n"
"border: 3px solid  #0f433d;\n"
"border-radius: 10px;\n"
"background-color: #cbddd1;")
        self.lineEditGoi.setObjectName("lineEditGoi")
        self.verticalLayout_10.addWidget(self.lineEditGoi)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButtonConhan = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButtonConhan.setMinimumSize(QtCore.QSize(50, 40))
        self.pushButtonConhan.setStyleSheet("background-color: rgb(78, 170, 28);")
        self.pushButtonConhan.setObjectName("pushButtonConhan")
        self.horizontalLayout_10.addWidget(self.pushButtonConhan)
        self.pushButtonHethan = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButtonHethan.setMinimumSize(QtCore.QSize(50, 40))
        self.pushButtonHethan.setStyleSheet("background-color: rgb(255, 138, 138);")
        self.pushButtonHethan.setObjectName("pushButtonHethan")
        self.horizontalLayout_10.addWidget(self.pushButtonHethan)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7.addLayout(self.verticalLayout_10)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_9.addWidget(self.widget_2)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_11.addItem(spacerItem1)
        self.label_9 = QtWidgets.QLabel(parent=self.widget)
        self.label_9.setMinimumSize(QtCore.QSize(0, 60))
        self.label_9.setStyleSheet("font: 87 18pt \"Noto Sans HK Black\";\n"
"background-color:#f6f6e9;\n"
"border-radius: 20px;\n"
"border: 3px ;")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_11.addWidget(self.label_9)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setStyleSheet("background-color:#f6f6e9;\n"
"border-radius: 20px;\n"
"border: 3px ;")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_10.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_11.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 1, 1, 1)
        self.labelNgayDKy = QtWidgets.QLabel(parent=self.widget_3)
        self.labelNgayDKy.setStyleSheet("font: 87 14pt \"Noto Sans HK Black\";")
        self.labelNgayDKy.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelNgayDKy.setObjectName("labelNgayDKy")
        self.gridLayout.addWidget(self.labelNgayDKy, 1, 0, 1, 1)
        self.labelNgayGiahan = QtWidgets.QLabel(parent=self.widget_3)
        self.labelNgayGiahan.setStyleSheet("font: 87 14pt \"Noto Sans HK Black\";")
        self.labelNgayGiahan.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelNgayGiahan.setObjectName("labelNgayGiahan")
        self.gridLayout.addWidget(self.labelNgayGiahan, 1, 1, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayout)
        self.verticalLayout_11.addWidget(self.widget_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButtonGiahan = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonGiahan.setMinimumSize(QtCore.QSize(170, 50))
        self.pushButtonGiahan.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButtonGiahan.setStyleSheet("color:rgb(0, 94, 69);\n"
"background-color: #f6f6e9;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 20px;\n"
"border: 3px solid  #58827d;")
        self.pushButtonGiahan.setIconSize(QtCore.QSize(30, 50))
        self.pushButtonGiahan.setObjectName("pushButtonGiahan")
        self.horizontalLayout_8.addWidget(self.pushButtonGiahan)
        self.pushButtonKhonggiahan = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonKhonggiahan.setMinimumSize(QtCore.QSize(170, 50))
        self.pushButtonKhonggiahan.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButtonKhonggiahan.setStyleSheet("color:#0f433d;\n"
"background-color: #cbddd1;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 20px;\n"
"border: 3px solid  #58827d;")
        self.pushButtonKhonggiahan.setIconSize(QtCore.QSize(30, 50))
        self.pushButtonKhonggiahan.setObjectName("pushButtonKhonggiahan")
        self.horizontalLayout_8.addWidget(self.pushButtonKhonggiahan)
        self.pushButtonChinh = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonChinh.setMinimumSize(QtCore.QSize(170, 50))
        self.pushButtonChinh.setStyleSheet("color:#0f433d;\n"
"background-color: #f6f6e9;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 20px;\n"
"border: 3px solid  #0f433d;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Nam1\\KTLT\\DoAn\\ui\\member\\../images/manager.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonChinh.setIcon(icon)
        self.pushButtonChinh.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonChinh.setObjectName("pushButtonChinh")
        self.horizontalLayout_8.addWidget(self.pushButtonChinh)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setStyleSheet("border-radius: 10px;\n"
"border: 3px ;\n"
"")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("D:\\Nam1\\KTLT\\DoAn\\ui\\member\\../../images/Screenshot 2026-03-17 143620.png"))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addWidget(self.widget)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1253, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonKhonggiahan_2.setText(_translate("MainWindow", "Back"))
        self.label.setText(_translate("MainWindow", "THÔNG TIN HỘI VIÊN"))
        self.label_2.setText(_translate("MainWindow", "Name:"))
        self.label_4.setText(_translate("MainWindow", "SĐT:"))
        self.label_5.setText(_translate("MainWindow", "Gender:"))
        self.label_6.setText(_translate("MainWindow", "Gói tập:"))
        self.label_7.setText(_translate("MainWindow", "Trạng thái:"))
        self.radioButtonMale.setText(_translate("MainWindow", "Male"))
        self.radioButtonFemale.setText(_translate("MainWindow", "Female"))
        self.pushButtonConhan.setText(_translate("MainWindow", "Còn hạn"))
        self.pushButtonHethan.setText(_translate("MainWindow", "Hết hạn"))
        self.label_9.setText(_translate("MainWindow", "Thông tin gói tập"))
        self.label_10.setText(_translate("MainWindow", "Ngày đăng ký"))
        self.label_11.setText(_translate("MainWindow", "Ngày gia hạn"))
        self.labelNgayDKy.setText(_translate("MainWindow", "8/3/2026"))
        self.labelNgayGiahan.setText(_translate("MainWindow", "1/4/2026"))
        self.pushButtonGiahan.setText(_translate("MainWindow", "GIA HẠN GÓI TẬP"))
        self.pushButtonKhonggiahan.setText(_translate("MainWindow", "KHÔNG GIA HẠN"))
        self.pushButtonChinh.setText(_translate("MainWindow", "CHỈNH SỬA HỒ SƠ"))
